#ifndef __BOARD_INFO_H__
#define __BOARD_INFO_H__

#include "stm32f4xx_hal.h"

#define CONFIG_ARCH_TYPE  ARCH_ARM_CM4

#define KEY1_PIN          GPIOE, GPIO_PIN_10
#define KEY2_PIN          GPIOE, GPIO_PIN_11
#define KEY3_PIN          GPIOE, GPIO_PIN_12

#define LED1_PIN          GPIOE, GPIO_PIN_13
#define LED2_PIN          GPIOE, GPIO_PIN_14
#define LED3_PIN          GPIOE, GPIO_PIN_15

#define DS18B20_DQ_PIN    GPIOE, GPIO_PIN_2

#define RS232_TX_PIN      GPIOA, GPIO_PIN_9
#define RS232_RX_PIN      GPIOA, GPIO_PIN_10
#define RS232_UART_PORT   USART1

#define RS485_TX_PIN      GPIOD, GPIO_PIN_5
#define RS485_RX_PIN      GPIOD, GPIO_PIN_6
#define RS485_RTS_PIN     GPIOD, GPIO_PIN_7
#define RS485_UART_PORT   USART2

#define CAN1_TX_PIN       GPIOD, GPIO_PIN_1
#define CAN1_RX_PIN       GPIOD, GPIO_PIN_0
#define CAN1_PORT         CAN1

#define CAN2_TX_PIN       GPIOB, GPIO_PIN_6
#define CAN2_RX_PIN       GPIOB, GPIO_PIN_5
#define CAN2_PORT         CAN2

#define AT24C02_SCL_PIN   GPIOB, GPIO_PIN_8
#define AT24C02_SDA_PIN   GPIOB, GPIO_PIN_9
#define AT24C02_I2C_PORT  I2C1

#define W25Q128_MOSI_PIN  GPIOC, GPIO_PIN_3
#define W25Q128_MISO_PIN  GPIOC, GPIO_PIN_2
#define W25Q128_SCLK_PIN  GPIOB, GPIO_PIN_10
#define W25Q128_CS_PIN    GPIOE, GPIO_PIN_3
#define W25Q128_SPI_PORT  SPI2

#define NRF24L01_MOSI_PIN GPIOC, GPIO_PIN_3
#define NRF24L01_MISO_PIN GPIOC, GPIO_PIN_2
#define NRF24L01_SCLK_PIN GPIOB, GPIO_PIN_10
#define NRF24L01_CE_PIN   GPIOE, GPIO_PIN_7
#define NRF24L01_CS_PIN   GPIOE, GPIO_PIN_8
#define NRF24L01_IRQ_PIN  GPIOE, GPIO_PIN_9
#define NRF24L01_SPI_PORT SPI2

#define USB1_DP_PIN       GPIOA, GPIO_PIN_12
#define USB1_DM_PIN       GPIOA, GPIO_PIN_11
#define USB2_DP_PIN       GPIOB, GPIO_PIN_15
#define USB2_DM_PIN       GPIOB, GPIO_PIN_14

#define TFCARD_DAT0_PIN   GPIOC, GPIO_PIN_8
#define TFCARD_DAT1_PIN   GPIOC, GPIO_PIN_9
#define TFCARD_DAT2_PIN   GPIOC, GPIO_PIN_10
#define TFCARD_DAT3_PIN   GPIOC, GPIO_PIN_11
#define TFCARD_CMD_PIN    GPIOD, GPIO_PIN_2
#define TFCARD_DET_PIN    GPIOD, GPIO_PIN_3
#define TFCARD_SPI  // SDIO

#endif
