#ifndef __PINMAP_H__
#define __PINMAP_H__

#define BOARD_STM32G070RB_UMOTION

#define LED1_PIN          GPIOC, GPIO_PIN_9
#define LED2_PIN          GPIOD, GPIO_PIN_0

#define KEY1_PIN          GPIOD, GPIO_PIN_1
#define KEY2_PIN          GPIOD, GPIO_PIN_2
#define KEY3_PIN          GPIOD, GPIO_PIN_3

#define OLED091_I2C_PORT  I2C1
#define OLED091_SCL_PIN   GPIOB, GPIO_PIN_8
#define OLED091_SDA_PIN   GPIOB, GPIO_PIN_7
#define OLED091_RST_PIN   GPIOB, GPIO_PIN_9  // nrst

#define AINI_POT1_PIN     GPIOA, GPIO_PIN_4
#define AINI_POT2_PIN     GPIOA, GPIO_PIN_5

#define RS485_TX1_PIN     GPIOC, GPIO_PIN_4
#define RS485_RX1_PIN     GPIOC, GPIO_PIN_5
#define RS485_RTS1_PIN    GPIOB, GPIO_PIN_1

#define RS485_TX2_PIN     GPIOB, GPIO_PIN_10
#define RS485_RX2_PIN     GPIOB, GPIO_PIN_11
#define RS485_RTS2_PIN    GPIOB, GPIO_PIN_12

#define TFORMAT_UART_PORT USART3

#define ADC_IW_PIN        GPIOA, GPIO_PIN_0
#define ADC_IU_PIN        GPIOA, GPIO_PIN_1
#define ADC_TEMP_PIN      GPIOA, GPIO_PIN_2
#define ADC_VBUS_PIN      GPIOA, GPIO_PIN_3

#define PWM_UL_PIN        GPIOB, GPIO_PIN_13
#define PWM_VL_PIN        GPIOB, GPIO_PIN_14
#define PWM_WL_PIN        GPIOB, GPIO_PIN_15
#define PWM_UH_PIN        GPIOA, GPIO_PIN_8
#define PWM_VH_PIN        GPIOA, GPIO_PIN_9
#define PWM_WH_PIN        GPIOA, GPIO_PIN_10

#endif
