
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVE_H
#define SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Servo_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Servo_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Servo_Data;
extern UNS8 spd_u16SpdSrc;		/* Mapped at index 0x2000, subindex 0x01 */
extern INTEGER16 spd_s16SpdTgt;		/* Mapped at index 0x2000, subindex 0x02 */
extern INTEGER16 spd_s16SpdFbk;		/* Mapped at index 0x2000, subindex 0x03 */
extern INTEGER16 spd_s16SpdRefSel;		/* Mapped at index 0x2000, subindex 0x04 */
extern INTEGER16 spd_s16SpdRef0;		/* Mapped at index 0x2000, subindex 0x05 */
extern INTEGER16 spd_s16SpdRef1;		/* Mapped at index 0x2000, subindex 0x06 */
extern INTEGER16 spd_s16SpdRef2;		/* Mapped at index 0x2000, subindex 0x07 */
extern INTEGER16 spd_s16SpdRef3;		/* Mapped at index 0x2000, subindex 0x08 */
extern INTEGER16 spd_s16SpdRef4;		/* Mapped at index 0x2000, subindex 0x09 */
extern INTEGER16 spd_s16SpdRef5;		/* Mapped at index 0x2000, subindex 0x0A */
extern INTEGER16 spd_s16SpdRef6;		/* Mapped at index 0x2000, subindex 0x0B */
extern INTEGER16 spd_s16SpdRef7;		/* Mapped at index 0x2000, subindex 0x0C */
extern INTEGER16 spd_s16SpdRef8;		/* Mapped at index 0x2000, subindex 0x0D */
extern INTEGER16 spd_s16SpdRef9;		/* Mapped at index 0x2000, subindex 0x0E */
extern INTEGER16 spd_s16SpdRef10;		/* Mapped at index 0x2000, subindex 0x0F */
extern INTEGER16 spd_s16SpdRef11;		/* Mapped at index 0x2000, subindex 0x10 */
extern INTEGER16 spd_s16SpdRef12;		/* Mapped at index 0x2000, subindex 0x11 */
extern INTEGER16 spd_s16SpdRef13;		/* Mapped at index 0x2000, subindex 0x12 */
extern INTEGER16 spd_s16SpdRef14;		/* Mapped at index 0x2000, subindex 0x13 */

#endif // SLAVE_H
