#include "paraattr.h"

// clang-format off
const para_attr_t sDeviceAttr[] = {
    {    WL(40020600),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0000 u32DevSchemeWL
    {    WH(40020600),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0000 u32DevSchemeWH
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0002 _Resv2
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0003 _Resv3
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV | B_DOB0 |    B_NR | B_ANYONE }, // P0004 u32McuSwBuildDateWL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV | B_DOB1 |    B_NR | B_ANYONE }, // P0004 u32McuSwBuildDateWH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV | B_DOB0 |    B_NR | B_ANYONE }, // P0006 u32McuSwBuildTimeWL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV | B_DOB1 |    B_NR | B_ANYONE }, // P0006 u32McuSwBuildTimeWH
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0008 _Resv8
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0009 _Resv9
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG | B_RL_UP | B_ANYONE }, // P0010 u16LedNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG | B_RL_DN | B_ANYONE }, // P0011 u16ExtDiNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_RL | B_ANYONE }, // P0012 u16ExtDoNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0013 u16ExtHDiNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0014 u16ExtHDoNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0015 u16ExtAiNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0016 u16ExtAoNum
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0017 _Resv17
    {          W(330),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC | B_NCOV |  B_SIG |    B_NR |  B_ADMIN }, // P0018 u16UaiHwCoeff
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0019 _Resv19
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0020 _Resv20
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0021 _Resv21
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0022 u16SysPwd
    {            W(0),            W(0),            W(2),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0023 u16SysAccess
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0024 bSwRstCmd
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0025 _Resv25
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0026 _Resv26
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0027 _Resv27
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0028 _Resv28
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0029 u16DiState
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0030 u16DoState
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0031 _Resv31
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0032 s16Uai0Si
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0033 s16Uai1Si
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0034 s16Uai2Si
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0035 s16Uai3Si
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0036 _Resv36
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0037 u16Uai0FltrTime
    {         W(1000),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0038 u16Uai0Zoom
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 | B_SIGN |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0039 s16Uai0Offset
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0040 u16Uai0DeadZone
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0041 u16Uai1FltrTime
    {         W(1000),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0042 u16Uai1Zoom
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 | B_SIGN |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0043 s16Uai1Offset
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0044 u16Uai1DeadZone
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0045 u16Uai2FltrTime
    {         W(1000),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0046 u16Uai2Zoom
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 | B_SIGN |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0047 s16Uai2Offset
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0048 u16Uai2DeadZone
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0049 u16Uai3FltrTime
    {         W(1000),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0050 u16Uai3Zoom
    {            W(0),      W(S16_MIN),      W(S16_MAX), B_RW_M0 | B_SIGN |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0051 s16Uai3Offset
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0052 u16Uai3DeadZone
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0053 _Resv53
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0054 _Resv54
    {            W(0),            W(0),            W(1), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0055 bPulOutEn
    {           WL(0),           WL(0),     WL(U32_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0056 u32PulOutCntWL
    {           WH(0),           WH(0),     WH(U32_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0056 u32PulOutCntWH
    {       WL(10000),           WL(1),    WL(40000000), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0058 u32PulOutFreqWL
    {       WH(10000),           WH(1),    WH(40000000), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0058 u32PulOutFreqWH
    {          W(500),            W(0),         W(1000), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0060 u16PulOutDuty
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0061 _Resv61
    {            W(1),            W(0),            W(1), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0062 bPulInEn
    {            W(1),            W(0),            W(4), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0063 u16PulInMode
    {           W0(0),     W0(S64_MIN),     W0(S64_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV | B_QUD0 |    B_NR | B_ANYONE }, // P0064 s64PulInCntW0
    {           W1(0),     W1(S64_MIN),     W1(S64_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV | B_QUD1 |    B_NR | B_ANYONE }, // P0064 s64PulInCntW1
    {           W2(0),     W2(S64_MIN),     W2(S64_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV | B_QUD2 |    B_NR | B_ANYONE }, // P0064 s64PulInCntW2
    {           W3(0),     W3(S64_MIN),     W3(S64_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV | B_QUD3 |    B_NR | B_ANYONE }, // P0064 s64PulInCntW3
    {        WL(2500),           WL(1),     WL(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0068 u32EncResWL
    {        WH(2500),           WH(1),     WH(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0068 u32EncResWH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0070 u32EncPosWL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0070 u32EncPosWH
    {           WL(0),     WL(S32_MIN),     WL(S32_MAX),    B_RO | B_SIGN |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0072 s32EncTurnsWL
    {           WH(0),     WH(S32_MIN),     WH(S32_MAX),    B_RO | B_SIGN |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0072 s32EncTurnsWH
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0074 _Resv74
    {            W(0),            W(0),            W(1), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0075 bFlexPulOutEn
    {       WL(10000),           WL(1),    WL(50000000), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0076 u32FlexPulOutFreqWL
    {       WH(10000),           WH(1),    WH(50000000), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0076 u32FlexPulOutFreqWH
    {            W(0),            W(0),           W(63), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0078 u16FlexPulOutStartIndex
    {            W(1),            W(0),           W(63), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0079 u16FlexPulOutStopIndex
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0080 _Resv80
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0081 u16FlexPulOutData00
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0082 u16FlexPulOutData01
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0083 u16FlexPulOutData02
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0084 u16FlexPulOutData03
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0085 u16FlexPulOutData04
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0086 u16FlexPulOutData05
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0087 u16FlexPulOutData06
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0088 u16FlexPulOutData07
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0089 u16FlexPulOutData08
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0090 u16FlexPulOutData09
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0091 u16FlexPulOutData10
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0092 u16FlexPulOutData11
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0093 u16FlexPulOutData12
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0094 u16FlexPulOutData13
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0095 u16FlexPulOutData14
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0096 u16FlexPulOutData15
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0097 u16FlexPulOutData16
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0098 u16FlexPulOutData17
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0099 u16FlexPulOutData18
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0100 u16FlexPulOutData19
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0101 u16FlexPulOutData20
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0102 u16FlexPulOutData21
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0103 u16FlexPulOutData22
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0104 u16FlexPulOutData23
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0105 u16FlexPulOutData24
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0106 u16FlexPulOutData25
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0107 u16FlexPulOutData26
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0108 u16FlexPulOutData27
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0109 u16FlexPulOutData28
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0110 u16FlexPulOutData29
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0111 u16FlexPulOutData30
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0112 u16FlexPulOutData31
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0113 u16FlexPulOutData32
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0114 u16FlexPulOutData33
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0115 u16FlexPulOutData34
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0116 u16FlexPulOutData35
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0117 u16FlexPulOutData36
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0118 u16FlexPulOutData37
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0119 u16FlexPulOutData38
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0120 u16FlexPulOutData39
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0121 u16FlexPulOutData40
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0122 u16FlexPulOutData41
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0123 u16FlexPulOutData42
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0124 u16FlexPulOutData43
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0125 u16FlexPulOutData44
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0126 u16FlexPulOutData45
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0127 u16FlexPulOutData46
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0128 u16FlexPulOutData47
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0129 u16FlexPulOutData48
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0130 u16FlexPulOutData49
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0131 u16FlexPulOutData50
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0132 u16FlexPulOutData51
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0133 u16FlexPulOutData52
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0134 u16FlexPulOutData53
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0135 u16FlexPulOutData54
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0136 u16FlexPulOutData55
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0137 u16FlexPulOutData56
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0138 u16FlexPulOutData57
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0139 u16FlexPulOutData58
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0140 u16FlexPulOutData59
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0141 u16FlexPulOutData60
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0142 u16FlexPulOutData61
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0143 u16FlexPulOutData62
    {            W(0),            W(0),           W(15), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0144 u16FlexPulOutData63
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0145 _Resv145
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0146 _Resv146
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0147 eDi0FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0148 u16Di0FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0149 eDi0LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0150 eDi1FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0151 u16Di1FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0152 eDi1LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0153 eDi2FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0154 u16Di2FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0155 eDi2LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0156 eDi3FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0157 u16Di3FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0158 eDi3LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0159 eDi4FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0160 u16Di4FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0161 eDi4LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0162 eDi5FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0163 u16Di5FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0164 eDi5LogicLvl
    {            W(1),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0165 eDi6FuncSel
    {            W(0),            W(0),      W(U16_MAX), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0166 u16Di6FltrTime
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0167 eDi6LogicLvl
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0168 _Resv168
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0169 u16DoStateSet
    {            W(1),            W(0),            W(7), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0170 eDo0FuncSel
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0171 eDo0LogicLvl
    {            W(1),            W(0),            W(7), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0172 eDo1FuncSel
    {            W(0),            W(0),            W(1), B_RW_M2 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0173 eDo1LogicLvl
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0174 _Resv174
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0175 s16TempMcuSi
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0176 _Resv176
    {            W(1),            W(1),          W(247), B_RW_M1 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0177 u16MbSlvId
    {       WL(19200),           WL(0),     WL(1000000), B_RW_M1 | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0178 u32MbBaudrateWL
    {       WH(19200),           WH(0),     WH(1000000), B_RW_M1 | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0178 u32MbBaudrateWH
    {            W(2),            W(0),            W(2), B_RW_M1 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0180 u16MbParity
    {            W(0),            W(0),            W(1), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0181 u16MbMstEndian
    {         W(5000),      W(U16_MIN),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0182 u16MbDisconnTime
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0183 u16MbResponseDelay
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0184 _Resv184
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0185 _Resv185
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0186 u16TunerBuff01
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0187 u16TunerBuff02
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0188 u16TunerBuff03
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0189 u16TunerBuff04
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0190 u16TunerBuff05
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0191 u16TunerBuff06
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0192 u16TunerBuff07
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0193 u16TunerBuff08
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0194 u16TunerBuff09
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0195 u16TunerBuff10
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0196 u16TunerBuff11
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0197 u16TunerBuff12
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0198 u16TunerBuff13
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0199 u16TunerBuff14
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0200 u16TunerBuff15
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0201 u16TunerBuff16
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0202 u16TunerBuff17
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0203 u16TunerBuff18
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0204 u16TunerBuff19
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0205 u16TunerBuff20
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0206 u16TunerBuff21
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0207 u16TunerBuff22
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0208 u16TunerBuff23
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0209 u16TunerBuff24
    {            W(0),            W(0),      W(U16_MAX), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0210 u16TunerBuff25
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0211 _Resv211
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0212 _Resv212
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0213 _Resv213
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0214 u16AlmCodeSeq
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0215 u16LastAlmCode
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0216 u16HisAlmCode01
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0217 u16HisAlmCode02
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0218 u16HisAlmCode03
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0219 u16HisAlmCode04
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV |  B_SIG |    B_NR | B_ANYONE }, // P0220 u16HisAlmCode05
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0221 u32HisAlmTime01WL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0221 u32HisAlmTime01WH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0223 u32HisAlmTime02WL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0223 u32HisAlmTime02WH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0225 u32HisAlmTime03WL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0225 u32HisAlmTime03WH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0227 u32HisAlmTime04WL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0227 u32HisAlmTime04WH
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0229 u32HisAlmTime05WL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0229 u32HisAlmTime05WH
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0231 _Resv231
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0232 _Resv232
    {            W(0),            W(0),            W(4),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0233 eSysState
    {           WL(0),           WL(0),     WL(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB0 |    B_NR | B_ANYONE }, // P0234 u32SysRunTimeWL
    {           WH(0),           WH(0),     WH(U32_MAX),    B_RO | B_UNSI |  B_SYNC |  B_COV | B_DOB1 |    B_NR | B_ANYONE }, // P0234 u32SysRunTimeWH
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0236 _Resv236
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0237 _Resv237
    {            W(0),            W(0),            W(8), B_RW_M0 | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0238 u16HrTimerSel
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0239 u16CycleScanTime
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0240 u16IsrScanTime
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0241 u16CustomTime0
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0242 u16CustomTime1
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0243 _Resv243
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0244 s16Uai0Pu
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0245 s16Uai1Pu
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0246 s16Uai2Pu
    {            W(0),      W(S16_MIN),      W(S16_MAX),    B_RO | B_SIGN | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0247 s16Uai3Pu
    {            W(0),            W(0),         W(4095),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0248 u16TempMcuPu
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0249 _Resv249
    {            W(0),            W(0),      W(U16_MAX),    B_RO | B_UNSI | B_NSYNC | B_NCOV |  B_SIG |    B_NR | B_ANYONE }, // P0250 _Resv250
};
// clang-format on
